In [1]:
# Numpy import
import numpy as np

In [3]:
a = [1,2,3,4,5]
for i in range(len(a)):
    a[i] += 15
    
print(a)

[16, 17, 18, 19, 20]


### numpy array를 따로 지정

In [4]:
a = np.array(a)
print(a)

[16 17 18 19 20]


In [5]:
a

array([16, 17, 18, 19, 20])

#### 참고) 위의 경우와 유사한 예제: 대상이 2개

In [8]:
a = [1,2,3,4,5,6,7,8,9,10]
b = [11,12,13,14,15,16,17,18,19,20]

a = np.array(a)
b = np.array(b)
print(a+b)

[12 14 16 18 20 22 24 26 28 30]


#### 이런식으로도 쓰인다

In [13]:
#arr_a = numpy.array([1,2,3,4,5,6,7,8,9,10]) package 이름 따로 지정안했을 시
arr_a = np.array([1,2,3,4,5,6,7,8,9,10])
arr_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 기본 정보 확인 : 차원(ndim), 모습(shape), 타입(ntype)

#### 어레이 원소에도 다른 형식도 가능

In [16]:
data = [[1,2,3,4],2,3,[7,8,9,10,11,[2,3,4,5]]]
arr_data = np.array(data)
print(arr_data)
print(arr_data.dtype) # object

[list([1, 2, 3, 4]) 2 3 list([7, 8, 9, 10, 11, [2, 3, 4, 5]])]
object


In [20]:
data1 = [[1,2,3,4],[1,3,5,7]]
arr_data1 = np.array(data1)
print(arr_data1)
print(arr_data1.dtype) # int 32
# 리스트 안에 같은 형식의 데이터(여기선 list를 넣음)를 넣으면 int로 인식
print(arr_data1.shape)
print(arr_data1.ndim)
# 2차원 array로 인식 / 2행 4열 array

[[1 2 3 4]
 [1 3 5 7]]
int32
(2, 4)
2


#### 형식을 미리 지정할 수도 있다. (여기선 int -> string으로 바뀜)

In [27]:
arr2 = np.array([1,2,3],dtype=np.string_)
arr2

array([b'1', b'2', b'3'], dtype='|S1')

#### for loop을 통해서 두개의 배열을 더할 때의 시간비용

In [32]:
import time
size_vector = 10000000

def pythonlist(size_vector):
    t1 = time.time()
    x = range(size_vector)
    y = range(size_vector)
    t2 = time.time()
    print("python list Load Time : " + str(t2-t1))
    z = []
    
    t3 = time.time()
    for i in range(len(x)):
        z.append(x[i] + y[i])
    t4 = time.time()
    print("python list for loop: " + str(t4-t3))
    print("Total: "+str(t4-t1))

pythonlist(size_vector)

python list Load Time : 0.0
python list for loop: 4.376448392868042
Total: 4.377448558807373


### numpy array를 이용해 연산을 할시 걸리는 시간비용(훨씬 단축됨)

In [33]:

def numpyarray1(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print("numpy array1 Load Time : " + str(t2-t1))
    
    # numpy array를 이용해서 연산을 하면 for loop 돌리는 것보다 훨씬 빠르다.
    t3 = time.time()
    z = x + y
    t4 = time.time()
    print("numpy array1 for loop : " + str(t4-t3))
    
    print("numpy array1 Total : " + str(t4-t1))

numpyarray1(size_vector)

def numpyarray2(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print("numpy array2 Load Time : " + str(t2-t1))
    
    # numpy array를 이용해서 연산을 하면 for loop 돌리는 것보다 훨씬 빠르다.
    t3 = time.time()
    z = np.ndarray(size_vector)
    for i in range(len(x)):
        z[i] = x[i] + y[i]
    t4 = time.time()
    print("numpy array2 for loop : " + str(t4-t3))
   
    print("numpy array2 Total : " + str(t4-t1))
    
numpyarray2(size_vector)

numpy array1 Load Time : 0.03500199317932129
numpy array1 for loop : 0.021001338958740234
numpy array1 Total : 0.05600333213806152
numpy array2 Load Time : 0.031001806259155273
numpy array2 for loop : 4.217241525650024
numpy array2 Total : 4.24824333190918


### +는 __add__ 함수를, +=는 __iadd__함수를 사용한다.(완전히 다른 연산자) 
"a += b" 는 앞에 a타입을 유지한다.

In [7]:
import time

# list1 함수와 엄청난 시간차이가 존재
# 앞으로 += 처럼 사용해야겠다.
# + 와 +=는 아예 다르다. 
# +는 square리스트를 한번더 호출해서 더해주기 때문에 시간이 상당히 많이 소요된다.
def square_list0(N):
    squares = []
    for n in range(N):
        squares = squares + [n**2]
    return squares

def square_list1(N):
    squares = []
    for n in range(N):
        # 일반적으로 생성해서 더하는 방법
        squares += [n**2]
    return squares

def square_list2(N):
    squares = []
    for n in range(N):
        # append라고 이미 정의된 메소드 이용하는 방법
        squares.append(n**2)
    return squares

def square_list3(N):
    #동일한 방법이나 벡터연산으로 처리
    return [n**2 for n in range(N)]

# 시간이 확 줄어든다.
def square_array(N):
    # Vectorize the entire operation
    from numpy import arange
    return arange(N)**2

n = 100000
print("Number :", n)
t1 = time.time()
square_list0(n)
t2 = time.time()
print("List0-Try : ", t2-t1)

t1 = time.time()
square_list1(n)
t2 = time.time()
print("List1-Try : ", t2-t1)

t1 = time.time()
square_list2(n)
t2 = time.time()
print("List2-Try : ", t2-t1)

t1 = time.time()
square_list3(n)
t2 = time.time()
print("List3-Try : ", t2-t1)

t1 = time.time()
square_array(n)
t2 = time.time()
print("Array-Try : ", t2-t1)

Number : 100000
List0-Try :  24.80441427230835
List1-Try :  0.05500340461730957
List2-Try :  0.052002906799316406
List3-Try :  0.04800271987915039
Array-Try :  0.0


### 기본적인 색인: 파이썬의 리스트와 동일

In [10]:
# 색인
list1 = [1,2,3,4,5,6]
arr1 = np.array(list1)
print(list1)
print(arr1)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [11]:
# 정수 인덱스로 리스트와 1차원 numpy 배열 접근 -> 참고) 원본은 변경되지 않음!!
print(list1[0])
print(arr1[0])
print()
print(list1[1:3])
print(arr1[1:3])
print()
print(list1[3:])
print(arr1[3:])
print()
print(list1[:])
print(arr1[:])

1
1

[2, 3]
[2 3]

[4, 5, 6]
[4 5 6]

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


### 2차원 배열 연습문제

In [14]:
# row 만들기
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

In [13]:
# column 기준 만들기
np.arange(0, 51, 10)

array([ 0, 10, 20, 30, 40, 50])

In [15]:
# np.newaxis : 행과 열을 바꿔주는 것
np.arange(0, 51,10)[:,np.newaxis]

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [16]:
# 뒤에 행에 해당하는 리스트를 더해주면 알아서 칼럼기준으로 더해진다.
np.arange(0, 51,10)[:,np.newaxis] + [1,2,3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53]])

In [18]:
a = np.arange(0, 51,10)[:,np.newaxis] + np.arange(0, 6, 1)

In [19]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [24]:
a[:] # a[:][:]와 같다.

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [27]:
print(a[0])
print(a[0][1])

[0 1 2 3 4 5]
1


In [38]:
print(a[:,2])
print(a[0,3:5])
print(a[2::2,::2])
print(a[4:,4:])

[ 2 12 22 32 42 52]
[3 4]
[[20 22 24]
 [40 42 44]]
[[44 45]
 [54 55]]


### Boolean indexing 기본적인 기능
조건검색할 때 이용(True면 해당 위치의 값을 반환)

In [42]:
# Boolean indexing
arr1 = np.arange(10)
print(arr1)
print(arr1<5)
print(arr1[arr1<5]) # True에 해당하는 위치의 값들만 반환

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]


In [61]:
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])
# 참고 np.random.randint(low, high=None, size=None, dtype=T)
data = np.random.randint(low=30, high=100, size=(7,4)) # end point included
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[38 78 32 45]
 [33 72 70 74]
 [88 85 93 85]
 [45 73 45 54]
 [85 46 45 97]
 [68 78 99 40]
 [58 43 97 62]]


In [62]:
# 이름이 Bob인 사람들만 찾기
print(names == "Bob")
print(names[names=="Bob"])
print(len(names[names=="Bob"]))

[ True False False  True False False False]
['Bob' 'Bob']
2


In [63]:
# 순서에 따라 indexing하는 것이기에 data와 names 배열을 연결 안해도 search가능
print(data[names=="Bob"])
print(data[names=="Bob",0::2])

[[38 78 32 45]
 [45 73 45 54]]
[[38 32]
 [45 45]]


In [64]:
# Bob이 두명인데 처음 나온 Bob의 성적만 보고 싶을 때
data[names=="Bob"][0]
# Bob 두명에 대해 두개의 배열을 하나의 배열에 넣은 것이기에 2차원 배열
# 거기에 [0] 하면 첫번째 줄의 데이터들을 불러옴

array([38, 78, 32, 45])

In [65]:
data[(names=="Bob")|(names=="Will")] # ( ) or ( ) 이렇게 사용가능

array([[38, 78, 32, 45],
       [88, 85, 93, 85],
       [45, 73, 45, 54],
       [85, 46, 45, 97]])

In [66]:
data[data<= 70] = 0
data[data > 70] = 1
print(data)

[[0 1 0 0]
 [0 1 0 1]
 [1 1 1 1]
 [0 1 0 0]
 [1 0 0 1]
 [0 1 1 0]
 [0 0 1 0]]


#### numpy.where(조건): 조건에 해당하는 index 위치를 행과 열 array 두개로 반환해준다.
반환값은 tuple / 위 array는 row에 대한 정보, 아래 array는 column에 대한 정보를 의미

In [72]:
# 참고) 원하는 값을 찾을 때는 np.where을 사용
# 1로 패스한 사람들의 데이터만 찾ㄹ음 -> 결과가 어떠한 것을 의미하는지 잘 확인할 것!
np.where(data>0) # tuple 형식으로 return
# array 두개가 나오는데 위 array가 행의 index, 아래 array가 열의 index를 의미한다.

(array([0, 1, 1, 2, 2, 2, 2, 3, 4, 4, 5, 5, 6], dtype=int64),
 array([1, 1, 3, 0, 1, 2, 3, 1, 0, 3, 1, 2, 2], dtype=int64))

#### unique(): array안에 중복된 값을 unique한 하나로 축약

In [70]:
# 중복이 되어있기에 unique하게 하나씩만 가져온다.
# 어떤 사람이 패스했는지 나타내는 지표(정확히는 패스한 과목이 최소 1개 이상인 사람들)
print(np.unique(np.where(data>0)[0]))
print(names[np.unique(np.where(data>0)[0])]) # 실제 이름을 가져오고자 할 때

[0 1 2 3 4 5 6]
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


#### 모양변경: shape을 바꾸기 -> reshape

In [6]:
# Numpy Transform
arr = np.arange(32).reshape((8,4)) # 8행 4열
arr 
# 32개를 변형할 정확한 모양 크기를 넣어야 한다.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [9]:
# 크기가 안맞을 때 에러 발생
arr = arr.reshape((3,9))

ValueError: cannot reshape array of size 32 into shape (3,9)

In [10]:
# T: Transpose (가로, 세로 축을 뒤바꿔줌)
arr = arr.reshape((4,8))
print(arr)
print()
print(arr.T)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]

[[ 0  8 16 24]
 [ 1  9 17 25]
 [ 2 10 18 26]
 [ 3 11 19 27]
 [ 4 12 20 28]
 [ 5 13 21 29]
 [ 6 14 22 30]
 [ 7 15 23 31]]


### 기본적인 수학 함수

In [11]:
# ufunc / math
arr1 = np.arange(10)
print(arr1)
print(np.sqrt(arr1))


[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
