In [23]:
# Numpy import
import numpy as np

In [3]:
a = [1,2,3,4,5]
for i in range(len(a)):
    a[i] += 15
    
print(a)

[16, 17, 18, 19, 20]


numpy array를 따로 지정

In [4]:
a = np.array(a)
print(a)

[16 17 18 19 20]


In [5]:
a

array([16, 17, 18, 19, 20])

참고) 위의 경우와 유사한 예제: 대상이 2개

In [8]:
a = [1,2,3,4,5,6,7,8,9,10]
b = [11,12,13,14,15,16,17,18,19,20]

a = np.array(a)
b = np.array(b)
print(a+b)

[12 14 16 18 20 22 24 26 28 30]


이런식으로도 쓰인다

In [13]:
#arr_a = numpy.array([1,2,3,4,5,6,7,8,9,10]) package 이름 따로 지정안했을 시
arr_a = np.array([1,2,3,4,5,6,7,8,9,10])
arr_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

기본 정보 확인 : 차원(ndim), 모습(shape), 타입(ntype)

어레이 원소에도 다른 형식도 가능

In [16]:
data = [[1,2,3,4],2,3,[7,8,9,10,11,[2,3,4,5]]]
arr_data = np.array(data)
print(arr_data)
print(arr_data.dtype) # object

[list([1, 2, 3, 4]) 2 3 list([7, 8, 9, 10, 11, [2, 3, 4, 5]])]
object


In [20]:
data1 = [[1,2,3,4],[1,3,5,7]]
arr_data1 = np.array(data1)
print(arr_data1)
print(arr_data1.dtype) # int 32
# 리스트 안에 같은 형식의 데이터(여기선 list를 넣음)를 넣으면 int로 인식
print(arr_data1.shape)
print(arr_data1.ndim)
# 2차원 array로 인식 / 2행 4열 array

[[1 2 3 4]
 [1 3 5 7]]
int32
(2, 4)
2


형식을 미리 지정할 수도 있다. (여기선 int -> string으로 바뀜)

In [27]:
arr2 = np.array([1,2,3],dtype=np.string_)
arr2

array([b'1', b'2', b'3'], dtype='|S1')

for loop을 통해서 두개의 배열을 더할 때의 시간비용

In [32]:
import time
size_vector = 10000000

def pythonlist(size_vector):
    t1 = time.time()
    x = range(size_vector)
    y = range(size_vector)
    t2 = time.time()
    print("python list Load Time : " + str(t2-t1))
    z = []
    
    t3 = time.time()
    for i in range(len(x)):
        z.append(x[i] + y[i])
    t4 = time.time()
    print("python list for loop: " + str(t4-t3))
    print("Total: "+str(t4-t1))

pythonlist(size_vector)

python list Load Time : 0.0
python list for loop: 4.376448392868042
Total: 4.377448558807373


numpy array를 이용해 연산을 할시 걸리는 시간비용(훨씬 단축됨)

In [33]:

def numpyarray1(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print("numpy array1 Load Time : " + str(t2-t1))
    
    # numpy array를 이용해서 연산을 하면 for loop 돌리는 것보다 훨씬 빠르다.
    t3 = time.time()
    z = x + y
    t4 = time.time()
    print("numpy array1 for loop : " + str(t4-t3))
    
    print("numpy array1 Total : " + str(t4-t1))

numpyarray1(size_vector)

def numpyarray2(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print("numpy array2 Load Time : " + str(t2-t1))
    
    # numpy array를 이용해서 연산을 하면 for loop 돌리는 것보다 훨씬 빠르다.
    t3 = time.time()
    z = np.ndarray(size_vector)
    for i in range(len(x)):
        z[i] = x[i] + y[i]
    t4 = time.time()
    print("numpy array2 for loop : " + str(t4-t3))
   
    print("numpy array2 Total : " + str(t4-t1))
    
numpyarray2(size_vector)

numpy array1 Load Time : 0.03500199317932129
numpy array1 for loop : 0.021001338958740234
numpy array1 Total : 0.05600333213806152
numpy array2 Load Time : 0.031001806259155273
numpy array2 for loop : 4.217241525650024
numpy array2 Total : 4.24824333190918
